- hosts: localhost
  gather_facts: yes
  gather_subset:
    - network
    - mounts
  become: yes
  vars:
    ansible_python_interpreter: /usr/bin/python3
  collections:
    - cisco.csdac
  tasks:
    - import_role:
        name: csdac
