---
UBUNTU_VERSION_ID: "18.04"
CTOP_VERSION: "0.7.3"
DOCKER_COMPOSE_VERSION: "v2.18.1"
DOCKER_PACKAGES:
  - apt-transport-https
  - ca-certificates
  - curl
  - gnupg-agent
  - software-properties-common
  - python3
  - python3-pip
  - python3-apt
  - libssl-dev
  - wget
  - acl
DOCKER_PACKAGES_RHEL:
  - ca-certificates
  - curl
  - python3-pip
  - openssl
  - wget
  - gnupg2
  - acl
PYTHON_PACKAGES:
  - docker-py
  - cryptography
  - pyopenssl
MUSTER_CORE_SERVICES:
  - muster-etcd
  - muster-bee
  - muster-ui-backend
  - muster-ui
ETCD_TAG: 2.3.0-latest
BEE_TAG: 2.3.0-latest
UI_BE_TAG: 2.3.0-latest
UI_TAG: 2.3.0-latest
AZURE_CONNECTOR_TAG: 2.3.0-latest
AZURE_SERVICE_TAGS_CONNECTOR_TAG: 2.3.0-latest
FMC_ADAPTER_TAG: 2.3.0-latest
AWS_CONNECTOR_TAG: 2.3.0-latest
VCENTER_CONNECTOR_TAG: 2.3.0-latest
O365_CONNECTOR_TAG: 2.3.0-latest
ENVOY_TAG: 2.3.0-latest
GCP_CONNECTOR_TAG: 2.3.0-latest
GITHUB_CONNECTOR_TAG: 2.3.0-latest
WEBEX_CONNECTOR_TAG: 2.3.0-latest
ZOOM_CONNECTOR_TAG: 2.3.0-latest
