- name: configure journald
  template:
    src: journald.conf.j2
    dest: /etc/systemd/journald.conf
  register: journald_conf
  notify:
    - restart journald

- name: ensure journald is started and enabled
  service:
    name: "systemd-journald"
    state: started
    enabled: yes
