---
- name: Ensure old versions of Docker are not installed.
  package:
    name:
      - docker
      - docker-engine
    state: absent

- name: Install packages needed for Docker
  package:
    update_cache: "yes"
    name: "{{ DOCKER_PACKAGES }}"
    state: present

- name: Ensure additional dependencies are installed (on Ubuntu < 20.04 and any other systems).
  package:
    name: gnupg2
    state: present
  when: ansible_distribution != 'Ubuntu' or ansible_distribution_version is version('20.04', '<')

- name: Ensure additional dependencies are installed (on Ubuntu >= 20.04).
  package:
    name: gnupg
    state: present
  when: ansible_distribution == 'Ubuntu' or ansible_distribution_version is version('20.04', '>=')

- name: Add Docker GPG apt Key
  apt_key:
    data: "{{ lookup('url', 'https://download.docker.com/linux/ubuntu/gpg', split_lines=False) }}"
    state: present
  environment:
    http_proxy: "{{csdac_role_https_proxy_url}}"
    https_proxy: "{{csdac_role_https_proxy_url}}"
    no_proxy: "{{ csdac_role_no_proxy }}"

- name: Save the current Ubuntu release version into a variable
  shell: lsb_release -cs
  register: ubuntu_version

- name: Add Docker Repository
  apt_repository:
    repo: "deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ ubuntu_version.stdout }} stable"
    state: present

