---
# ansible distribution
ansible_distribution: "Ubuntu"

# csdac docker images tags
ETCD_TAG: 2.0.0-latest
BEE_TAG: 2.0.0-latest
UI_BE_TAG: 2.0.0-latest
UI_TAG: 2.0.0-latest
AZURE_CONNECTOR_TAG: 2.0.0-latest
AZURE_SERVICE_TAGS_CONNECTOR_TAG: 2.0.0-latest
FMC_ADAPTER_TAG: 2.0.0-latest
AWS_CONNECTOR_TAG: 2.0.0-latest
VCENTER_CONNECTOR_TAG: 2.0.0-latest
O365_CONNECTOR_TAG: 2.0.0-latest
GCP_CONNECTOR_TAG: 2.0.0-latest
ENVOY_TAG: 2.0.0-latest

# defaults file for muster-ansible
journald_storage_option: "persistent"
journald_compress_option: "yes"
journald_seal_option: "yes"
journald_splitmode: "uid"
journald_sync_interval: "5m"
journald_rate_limit_interval: "30s"
journald_rate_limit_burst: "1000"
journald_system_max_use: ""
journald_system_keep_free: ""
journald_max_file_size: ""
journald_runtime_max_use: ""
journald_runtime_keep_free: ""
journald_runtime_max_file_size: ""
journald_max_retention_sec: ""
journald_max_file_sec: "1month"
journald_forward_to_syslog: "yes"
journald_forward_to_kmsg: "no"
journald_forward_to_console: "no"
journald_forward_to_wall: "yes"
journald_tty_path: "/dev/console"
journald_max_level_store: "debug"
journald_max_level_syslog: "debug"
journald_max_level_kmsg: "notice"
journald_max_level_console: "info"
journald_max_level_wall: "emerg"


csdac_role_certificate_domain: "{{ csdac_certificate_domain | default(ansible_fqdn or ansible_hostname) }}"
csdac_role_certificate_country_name: "{{ csdac_certificate_country_name | default('US') }}"
csdac_role_certificate_organization_name: "{{ csdac_certificate_organization_name | default('Cisco') }}"        
csdac_role_certificate_organization_unit_name: "{{ csdac_certificate_organization_unit_name | default('Cisco') }}"
csdac_role_proxy_enabled: "{{ csdac_proxy_enabled | default(False) }}"
csdac_role_http_proxy_url: "{{ csdac_http_proxy_url | default('') }}"
csdac_role_https_proxy_url: "{{ csdac_https_proxy_url | default('') }}"
csdac_role_no_proxy: "{{ csdac_no_proxy | default('') }}"